---@meta
-- GENERATED by `supervisor/src/stubs.rs` for obelisk 0.1.0. Do not edit: run `just stubs` and
-- commit what changes.
--
-- The only generated file in `lua-meta`. `nodes.lua`, `surfaces.lua`, `globals.lua` and
-- `signals.lua` are hand-written and `just stubs` does not touch them; each says so at its own top
-- and names what checks it. This one is derivable because a capability payload is a real
-- `Serialize` struct, and a node's schema is scattered `properties.get("...")` calls.
--
-- The version above is what `stub_version` reads. Stubs describing a different engine than the one
-- installed are worse than no stubs, because they are wrong with authority, so `obelisk init` says
-- so and refreshes them.
--
-- The capability classes below are the supervisor's own `Serialize` types, which is what
-- `push_snapshot` sends, so a field here is a field that crosses the socket. Descriptions are the
-- Rust doc comments on those fields. To document a field for config authors, write the doc comment
-- in Rust and regenerate.
--
-- A capability reads `nil` until its first `StateSnapshot` arrives, which every config sees on
-- every boot. A signal resolving to `nil` means the property is absent, so a bound node renders its
-- default rather than failing the tree (ADR-0044). A JSON `null` arrives as an absent key rather
-- than a sentinel (ADR-0057), so `if item.app_icon then` is the right guard for an optional field.

---@class Capability<T>: Signal<T>
---A capability is a signal you can also command. `:get()` and `:map()` read the pushed payload;
---`:invoke()` sends a command the supervisor dispatches. Read-only otherwise: `:set()` refuses it,
---or a config could overwrite the SSID the supervisor just pushed.
---
---Generic over the payload, and inherited as `Capability<NetworkState>` and so on below, which is
---what types the callback: the `n` in `obelisk.network:map(function(n) ... end)` is a `NetworkState`,
---so a misspelled field is an `undefined-field` here rather than a `nil` at runtime. `get`/`map`
---come from [`Signal`] and are not restated per capability; only `invoke` is, because each one
---knows its own command names.
---
---`:on_change(handler)` is the one place a config reacts to a push instead of rendering it
---(ADR-0115): the handler runs once per pushed snapshot with the new payload and the one it
---replaced (`nil` on the first push), outside any layout pass, under a `map` callback's 5ms CPU
---budget. It may do what an input callback may do: `invoke`, `process.run`, write a `state`
---signal. Compare the two payloads to find the edge you want; the engine hands over every push.
---@field invoke fun(self: Capability<T>, command: string, ...: any)
---@field on_change fun(self: Capability<T>, handler: fun(current: T, previous: T?))

--- Payload types ------------------------------------------------------------------------------

---@class AccessPointInfo
---One scanned AP, resolved to `network.available_networks` (docs/lua-api.md §2.5)
---and serialized in a `StateSnapshot` payload, same convention as `audio::mixer::AppStream`.
---@field active boolean This is the AP currently associated.
---@field band string `"2.4 GHz"`, `"5 GHz"` or `"6 GHz"`, from the AP's frequency.
---@field saved boolean A saved NetworkManager profile names this SSID, so joining it asks for no password.
---@field secure boolean A key is required: WEP privacy or non-empty WPA1/RSN key management.
---@field ssid string Network name. Entries dedupe on it, keeping the stronger sighting.
---@field strength integer Signal strength, `0` to `100`.

---@class ActiveClient
---§ 2.9's `active_client`. `is_fullscreen` is present only when reported (ADR-0056 decision 5
---rejects fabricated `false`; ADR-0119 lets Hyprland provide it). `class` is Wayland `app_id`;
---Wayland has no X11 `WM_CLASS` equivalent.
---@field class string Wayland `app_id`, e.g. `"firefox"`. Named `class` for X11 familiarity; use it with `applications.by_app_id`.
---@field is_floating boolean Whether the compositor floats this window rather than tiles it.
---@field is_fullscreen? boolean Whether the window covers its whole output. Absent when unreported (niri-ipc has no field, ADR-0056 decision 5); Hyprland reports it (ADR-0119).
---@field title string Window title, e.g. `"src/main.rs - Neovim"`; empty when unset.

---@class AppStream
---A `Stream/Output/Audio` node resolved to its owning process. `main.rs` publishes it unchanged;
---§ 2.4 names `id`/`name` (ADR-0053 decision 3), while ADR-0016's `pid`/`process_name` remain.
---@field id integer PipeWire registry id, the [`AudioApps`] key.
---@field muted boolean § 2.4 per-app mute, from the same `Props` as `volume`.
---@field name? string `application.name`, if the client set one.
---@field pid integer `application.process.id` recorded for the owning process.
---@field process_name? string `/proc/{pid}/comm`, if the process still existed when observed.
---@field volume number § 2.4 per-app volume, range `[0.0, 1.0]`, cube-rooted from `SPA_PARAM_Props` like a master sink (`pw-cli enum-params <id> Props` confirms cubed `channelVolumes`). `1.0` before it.

---@class AppSummary
---One application as config sees it (ADR-0061). Display data only: argv stays private because
---`applications:launch(id)` runs it, and exposing it would let config rewrite the command.
---@field comment? string Unlocalized `Comment=`, the one-line description/search text under the name, e.g. `"Web Browser"` under `Firefox` (ADR-0112). `None` means no key, so config can hide it; unlike `name`, this field is localized.
---@field generic_name? string Unlocalized `GenericName=`, what the application is rather than what it is called: `"Text Editor"` under `Zed`, which no other field of that entry says. Search text.
---@field icon? string `Icon=` as written, either a theme name or absolute path; `icon { name = ... }` accepts both (ADR-0054 decision 2). `None` means no `Icon=` key, distinct from failed resolution.
---@field id string Desktop file id (`org.telegram.desktop`), and `launch`'s argument.
---@field keywords string[] `Keywords=` split on `;`: the synonyms an entry ships for search, such as GIMP's `GNU` and `Image Manipulation Program`. Empty when the key is absent. Search text, not a label.
---@field name string Unlocalized `Name=`. `Name[xx]` is not read (ADR-0061), so this is English on a localized system.

---@class AudioDevice
---One § 2.4 `sinks`/`sources` entry. `name` is the user-facing `node.description`, not routing
---`node.name` (`"alsa_output.pci-0000_00_1f.3.analog-stereo"`).
---@field active boolean Whether `default.audio.sink`/`default.audio.source` currently routes here.
---@field icon? string PipeWire's `device.icon-name` hint, such as `"audio-card-analog"`; not resolved here. `None` means the node carried no hint, as with a virtual sink.
---@field id integer PipeWire registry id used by `audio:set_default_sink(id)`.
---@field name string Device description, e.g. `"Built-in Audio Analog Stereo"`; neither is reboot-stable.

---@alias BatteryStatus
---| "Unknown" # UPower has no answer, including hosts whose display device is not a battery.
---| "Charging" # Taking current; on this hardware that means an adapter is supplying it.
---| "Discharging" # Draining.
---| "Empty" # Flat; UPower reports this instead of `Discharging` only at the very end.
---| "FullyCharged" # Charged and holding. A battery stopped below full reports `PendingCharge` instead.
---| "PendingCharge" # Waiting to charge: not draining, not taking current.
---| "PendingDischarge" # Waiting to discharge, by name; UPower defines it no further.
---§ 2.2's `battery.state`, one of UPower's seven `Device.State` values.
---
---A boolean collapsed `PendingCharge` and `PendingDischarge` into `false`, making a battery that
---is merely not moving indistinguishable from one that is draining. On a laptop that sets
---`charge_control_end_threshold` -- 70 here -- the not-moving case is most of every day, which is
---why the state is carried by name. The three seen on this hardware are `Charging`,
---`PendingCharge` and `Discharging`.
---
---UPower documents these seven only as names: its `Device` page lists the enum and defines no
---value. So each doc below says what the kernel and this hardware were observed to do, and none
---of them is a guarantee from UPower.
---
---Serialized by name, so Lua compares `b.state == "PendingCharge"`; `mpris.play_state` uses the
---same boundary shape.

---@class ConnectedDevice
---@field battery integer Battery percentage, or `-1` if unsupported/unknown (no `Battery1`, or `Percentage` failed), per the IDL.
---@field busy? string Same as [`DiscoveredDevice::busy`].
---@field category string Drawing hint from the class of device: `"keyboard"`, `"mouse"`, `"headphones"`, `"headset"`, `"phone"`, `"computer"`, or `"generic"`. Choose an icon; it is not a capability.
---@field codec? string Always `None` for now; codec query/control is deferred (ADR-0030) to an `audio` capability with a live PipeWire `Device` proxy.
---@field mac string Canonical MAC address, e.g. `"00:1A:7D:DA:71:11"`; every `bluetooth:` command uses it.
---@field name string The device's advertised name.

---@class DiscoveredDevice
---@field blocked boolean BlueZ refuses to pair with or connect to the device until it is unblocked.
---@field busy? string `"pairing"`, `"connecting"` or `"disconnecting"` while this Supervisor's call for the device runs, or `nil`. A device can change lists mid-action, so any list can carry any label. BlueZ has no property for a call in flight, so a pair or connect started by another client or by the device itself never shows here.
---@field mac string Canonical MAC address accepted by `bluetooth:pair(mac)`.
---@field name string Advertised name, often empty when the device broadcasts only an address.
---@field paired boolean Always `false`; every entry in this pool is unpaired (IDL contract).

---@class FileEntry
---@field modified integer Last-modification Unix seconds for newest-first sorting; `0` when unavailable.
---@field name string File name alone, such as `sunrise.jpg`, for drawing and search.
---@field path string Absolute path for `image { source = ... }` and config storage.

---@class Folder
---@field entries FileEntry[] Plain files directly inside the folder, skipping dotfiles, filtered to `watch`'s extensions and sorted case-insensitively. Not recursive. Replaced wholesale after each debounced inotify burst, so a copy in progress lands as one update.
---@field error? string A drawable listing error such as `"No such file or directory"`, or absent on success. Set with `ready = true`, distinguishing a missing folder from an empty one.
---@field ready boolean `false` until the first listing lands, for a picker's loading spinner. `true` thereafter, even when `entries` is empty or `error` is set.

---@class IdleInhibitor
---One logind inhibitor blocking idle.
---@field who string Free-text `who` passed to `Inhibit`, e.g. `"mpv"`; draw it as a label, never match it.
---@field why string Free-text `why`, e.g. `"Playing video"`, often empty.

---@class MenuItem
---One DBusMenu layout node, resolved to `tray.items[].menu` (docs/lua-api.md §2.14).
---@field children MenuItem[] Nested entries from the single `GetLayout(0, -1)` reply, so no `tray:menu_will_show` is needed to populate them. Empty for leaves and for nodes at [`MAX_MENU_DEPTH`], whose children are dropped with an stderr line.
---@field enabled boolean `false` for a greyed-out entry. Activation is a no-op; keep it to preserve the application's layout instead of filtering it.
---@field icon_name? string Theme icon name, or `nil`; DBusMenu pixmaps are not carried.
---@field id integer DBusMenu item id used by `tray:activate_menu_item` and `tray:menu_will_show`.
---@field label? string Entry text exactly as sent, or `nil`. Separators normally have none. `_` mnemonic markers remain, so `"_Quit"` is sent as-is; strip it in config if you do not want the underscore drawn.
---@field menu_type string `"standard"` or `"separator"`. A separator carries no label and is not clickable.
---@field toggle_state? integer DBusMenu state: `0` off, `1` on, `-1` indeterminate. `nil` exactly when [`MenuItem::toggle_type`] is `nil`; a missing state with a toggle type becomes `-1`.
---@field toggle_type? string `"checkmark"`, `"radio"`, or `nil` for an entry that is not a toggle.

---@class Notification
---Queued `notifications.feed[]` object (idl §2.7; ADR-0033, ADR-0090). `expire_timeout` and
---`replaces_id` affect processing but are not feed data.
---@field actions NotificationAction[] Offered buttons in sender order, excluding `default` and `inline-reply`; often empty.
---@field app_icon? string Application icon: theme name (for example `"firefox"`) or trusted absolute path; `nil` if neither was supplied. Feeds `icon { name = ... }` (ADR-0054 decision 2). ADR-0091 fixed the former bug that sent theme names through absolute-path validation, leaving nearly every notification with the generic fallback.
---@field app_name string Sending application, truncated to 64 bytes at a character boundary.
---@field body NotificationSpan[] Body spans, truncated to 512 bytes before parsing. Text carries bold/italic/underline/href; images carry trusted paths, so config draws without parsing markup.
---@field desktop_entry? string `hints["desktop-entry"]` id, e.g. `"org.telegram.desktop"`, used by `obelisk.applications.by_app_id` (§ 2.13) instead of the mutable/non-unique `app_name`. `nil` when absent; slashed values are dropped (ADR-0101).
---@field expired boolean Whether the timeout expired. Ordinary expiry retires the entry from popups but leaves it in feed history (ADR-0100), after `NotificationClosed(id, reason=1)`; replacements reset it. Never true for critical or `expire_timeout = 0` notifications.
---@field has_default_action boolean Whether the card is activatable via `notifications:invoke_action(id, "default")`; separate from `actions` because `default` is not a button.
---@field has_reply boolean Whether the sender offered inline reply; `notifications:reply(id, text)` requires it.
---@field id integer Server id, starting at `1`; used by dismiss/reply/action and reused by replacement.
---@field image_path? string Attached picture (album art/avatar/thumbnail) as an existing absolute path: decoded image spooled to runtime storage or a trusted sender path. `nil` when absent; never a theme name (ADR-0091). Formerly shared `icon_path` with the application icon; now separate.
---@field reply_placeholder? string `hints["x-kde-reply-placeholder-text"]`: what the sender wants an empty reply field to say, "Reply to Alice" rather than a generic "Reply"; capped at 64 bytes, `nil` if absent, and meaningless without [`Notification::has_reply`] (ADR-0101).
---@field summary string Plain-text title, truncated to 128 bytes at a character boundary; markup is parsed out.
---@field timestamp integer Arrival time in Unix epoch seconds, matching `obelisk.system.time` (§2.11); age is `system.time - timestamp`. Replacements get fresh timestamps; carried because configs cannot recover history inside ADR-0021 side-effect-free `computed`s.
---@field transient boolean `hints["transient"]`: popup-only (§1). Expired transient entries are removed, not retired, so history never sees them (ADR-0100).
---@field urgency Urgency `"low"`, `"normal"`, or `"critical"`; missing hint means `"normal"`. Critical bypasses DND and never expires.

---@class NotificationAction
---One offered action button (ADR-0090), excluding `default` activation and `inline-reply`, which
---become [`Notification::has_default_action`] and [`Notification::has_reply`]. The flat array
---was once read for one bool and discarded, so `GetCapabilities` advertised `actions` and
---`action-icons` while neither was true; parsed buttons are retained now.
---@field icon_name? string Theme icon name when `action-icons` is set; never a path or resolved here. Keys containing `/` are refused to prevent a sender naming arbitrary files (ADR-0054 decision 2).
---@field key string Opaque key accepted by `notifications:invoke_action(id, key)` and returned as `ActionInvoked.action_key`.
---@field label string Button label, falling back to the key when empty unless the action is icon-only.

---@class NotificationSpan
---One allowlisted body-markup run (CONTEXT.md, ADR-0033). Text carries styling and link target;
---images carry only a spooled/validated path. `alt` is parsed but not carried.
---@field bold? boolean Whether the run was inside `<b>`.
---@field href? string `<a href>` target, or `nil` when not a link. Config decides whether to open it.
---@field image_path? string Existing absolute path under a trusted root; outside paths are dropped during parsing.
---@field italic? boolean Whether the run was inside `<i>`.
---@field kind "text"|"image"
---@field text? string Unescaped text; empty runs are omitted.
---@field underline? boolean Whether the run was inside `<u>`.

---@class OutputWorkspaces
---One output's workspace state; `workspaces` is ADR-0056 decision 3's addition to § 2.9.
---@field active_workspace integer [`WorkspaceEntry::id`] visible on this output; every output has one.
---@field focused_workspace? integer Present only on the focused output (ADR-0056 decision 4); `out.focused_workspace ~= nil` tests whether this is the focused monitor.
---@field name string Connector name, e.g. `"eDP-1"`; matches `obelisk.screens.name` and a surface's `monitor`.
---@field workspaces WorkspaceEntry[] Workspaces on this output, ordered by [`WorkspaceEntry::idx`]; the strip draws these because the two ids above are opaque.

---@class PairedDevice
---@field blocked boolean BlueZ refuses every connection to or from the device until it is unblocked.
---@field busy? string Same as [`DiscoveredDevice::busy`].
---@field category string Drawing hint, the same set as [`ConnectedDevice::category`].
---@field mac string Canonical MAC address accepted by `bluetooth:connect(mac)` and `bluetooth:forget(mac)`.
---@field name string The device's advertised name.

---@class PairingRequest
---What the pairing agent is asking the user, drawn by `modules/global/bluetooth_pairing.lua`.
---@field code? string Six-digit passkey or legacy PIN for `"confirm"` and `"display"`, else `nil`.
---@field kind string `"confirm"`: does the device show `code`? `"authorize"`: a device asks to pair. `"service"`: a paired but untrusted device asks to connect. `"display"`: type `code` on the device, with nothing to answer.
---@field mac string The device's MAC address.
---@field name string The device's advertised name, or empty.

---@class PlayerState
---@field album_art_path string Absolute artwork path, or empty. `mpris:artUrl` must be a `file://` URL canonicalizing to an existing file; remote/stale URLs become empty. Held across same-track updates so covers do not blink.
---@field artist string `xesam:artist`, joined with `", "`; empty when absent.
---@field desktop_entry string `MediaPlayer2.DesktopEntry`, the `.desktop` basename, e.g. `"mpv"` or `"firefox"`; empty when unpublished. Stable player name for app matching. `identity` is a display string that may localize or decorate.
---@field id string Bus-name suffix after `org.mpris.MediaPlayer2.`, e.g. `"spotify"`; used by `mpris:` commands.
---@field identity string `MediaPlayer2.Identity`, e.g. `"Spotify"`; empty if unanswered.
---@field length integer `-1` when `mpris:length` is absent or malformed, as for a live stream; unavailable is not fabricated as zero (ADR-0036).
---@field play_state string `"Playing"`, `"Paused"`, or `"Stopped"`; retains the previous value if the player fails.
---@field position integer Playback offset in microseconds, valid at [`PlayerState::position_updated_at`]. Nothing polls it while playing; progress bars add elapsed time. `-1` when the player has never answered `Position`, which is not the same as a track sitting at zero (ADR-0036).
---@field position_updated_at integer `CLOCK_MONOTONIC` microseconds when [`PlayerState::position`] was read; subtract from a monotonic `now` for elapsed time and survive wall-clock adjustments.
---@field title string `xesam:title`; empty when metadata is absent, normal between tracks.
---@field url string `xesam:url`, such as a local `file://` path or browser `https://` page; empty when absent, normal for a stream. Carried for ADR-0137: configs cannot reliably classify video versus song from site lists or extensions, which are taste-dependent.

---@class PrivacyUser
---An app using one watched resource. The `{app_name}` row shape from ADR-0034's
---`privacy.camera_users` extends to microphone and screencast under ADR-0137; one type keeps the
---three "who" lists identical.
---@field app_name string Process name from its PipeWire node, then `/proc/<pid>/comm`, then `"pid 1234"`; never empty.

---@class SessionProcess
---One declared program: its current run, or what is left of its last one.
---@field exit_code? integer How the last finished run ended: its exit status, `nil` while running, before the first run, or when a signal ended it rather than an exit. Cleared by the next `start`.
---@field pid? integer Its process id, which is also its process group. `nil` until the first `start`, and kept after an exit so a log line can still name what died.
---@field running boolean Whether it is up now. Every field below describes the current run while this is true, and the finished one while it is false.
---@field start_error string Why the last `start` produced no process at all -- a command that is not on `PATH`, most often. Empty when it spawned, and cleared by the next `start`. Without this a config waiting on `running` would wait forever with the reason only in the Supervisor's stderr.
---@field started_at? integer Unix seconds when the current or last run began; `nil` until the first `start`. Elapsed time is this subtracted from `obelisk.system`'s clock, so nothing here needs a second timer.

---@class SpecialWorkspace
---One special workspace (ADR-0119), identified by `name`, the argument to
---`workspaces:toggle_special(name)`; Hyprland uses names and negative ids.
---@field app_id? string `app_id` of its standing window, chosen as [`WorkspaceEntry::app_id`] is.
---@field name string Full compositor name, `"special:scratch"` or unnamed `"special"`.
---@field populated boolean Whether at least one window sits on it.
---@field shown_on? string Connector currently showing it, absent while hidden; a special shows on one output at a time.

---@class TrayItem
---@field attention_icon_name? string `NeedsAttention` artwork, resolved like `icon_name`/`icon_path`; draw it instead of the base pair when `status == "NeedsAttention"`. Both are `nil` when undeclared.
---@field attention_icon_path? string File half of the attention artwork, matching `attention_icon_name`.
---@field icon_name? string Theme icon name for `icon { name = ... }`; exclusive with [`TrayItem::icon_path`].
---@field icon_path? string Decoded, bounds-checked PNG in the runtime directory for `image { source = ... }`; set when the item sent pixels instead of a theme name.
---@field id string docs/lua-api.md §2.14 id: sanitized D-Bus unique name with the item's object path appended, e.g. `"1.234/StatusNotifierItem"`. Used by every `tray:` command.
---@field item_is_menu boolean `true` means left click opens the menu instead of activating the item.
---@field menu? MenuItem[] Top-level menu entries, or `nil` without `com.canonical.dbusmenu`. Fetched at registration and on layout updates.
---@field name string Display name: `Title`, falling back to `Id` when `Title` is empty.
---@field overlay_icon_name? string Badge to draw over the base icon's corner. Carried, not composited, because a `stack` node overlays images and the Supervisor has no canvas. Both are `nil` when undeclared.
---@field overlay_icon_path? string File half of the badge, matching `overlay_icon_name`.
---@field status string SNI status: `"Active"`, `"Passive"`, or `"NeedsAttention"`. `"Passive"` asks config to hide the item.
---@field tooltip? string Tooltip title and text flattened to one string, or `nil` when absent.

---@class UpdateCandidate
---One installed package with a newer version, also the `updates.packages` Lua shape.
---@field download_size integer Bytes to fetch; `0` when already cached.
---@field installed_size integer Bytes occupied unpacked, not a delta. Config subtracts the old size if needed.
---@field name string The package name, as the package manager spells it.
---@field new_version string Version offered by synced repositories.
---@field old_version string Installed version in the manager's spelling.

---@alias Urgency "low"|"normal"|"critical"
---`low`/`normal`/`critical` urgency tier, also used as the sound-registry key.

---@class WorkspaceEntry
---`id` is the stable, monitor-independent identity used by `active_workspace`,
---`focused_workspace`, and `workspaces:focus(id)`. `idx` is the output-local 1-based position,
---useful for labels but unstable across reorders.
---@field app_id? string Wayland `app_id` of its representative window: focused when focused, otherwise the compositor's first. Absent for empty workspaces or windows without an id; `nil` means draw the number.
---@field id integer Stable identity independent of output; the ids on [`OutputWorkspaces`] and `workspaces:focus(id)` use it.
---@field idx integer 1-based position on this output. Reorders renumber it, so draw `idx` but send `id`.
---@field name? string Compositor name, or `nil` when it has none; most do not.
---@field populated boolean Whether a window sits here (ADR-0117); strips dim empty workspaces.

---@class ApplicationsState
---`obelisk.applications`'s payload (ADR-0061 decision 2).
---
---`by_app_id` repeats summaries instead of indexing `entries`: Lua arrays start at one while the
---serialized JSON array starts at zero. Repeating three small fields for a few hundred entries
---avoids an invisible off-by-one.
---@field by_app_id table<string, AppSummary> The same entries keyed by a window's `app_id`, for callers holding `workspaces.active_client.class` rather than a desktop id. Exact `StartupWMClass` and desktop id win over case-folded and last-dot-segment spellings; exact keys are never displaced. A miss is only a heuristic miss, not proof that the app is uninstalled.
---@field entries AppSummary[] Visible, launchable installed entries, sorted by name. Rebuilt by `applications:refresh()`; directories are not watched, so mid-session installs wait for it.

---@class AudioState
---Full `obelisk.audio` payload (§ 2.4, ADR-0053 decision 3).
---@field apps AppStream[] One entry per app playing audio; empty is normal.
---@field muted boolean Master output mute.
---@field sinks AudioDevice[] Every output device; `audio:set_default_sink(id)` takes [`AudioDevice::id`].
---@field source_muted boolean Default input mute, the microphone-mute click target for privacy indicators (§ 3.2).
---@field source_volume number Default input volume, range `[0.0, 1.0]`, using the sink's cube-root conversion (`pw-cli enum-params <source> Props` has the same shape). `0.0` before first `Props` or with no input device.
---@field sources AudioDevice[] Every input device, on the same terms as [`AudioState::sinks`].
---@field volume number Master output volume, range `[0.0, 1.0]`, derived from the default sink's `channelVolumes`.

---@class BatteryState
---`obelisk.battery`'s full payload (§ 2.2). Field names are the `StateSnapshot` JSON keys verbatim
---and may not be renamed. `Default` is the correct desktop answer when no battery exists.
---@field percent integer Charge, `0` to `100`, rounded against the battery's full capacity, not its charge limit. A machine capped at 70 therefore reads `70`, not `100`.
---@field present boolean Whether UPower's display device is a battery and present. `false` on a desktop is an answer, not missing data; check it before drawing the other fields.
---@field state BatteryStatus UPower's state, including `PendingCharge` on mains versus `Discharging` on battery.
---@field time_to_empty? integer Seconds until flat, or `nil`. UPower reports `0` while charging and before it has estimated; neither is a duration.
---@field time_to_full? integer Seconds until full, or `nil` on the same terms as `time_to_empty`.

---@class IdleState
---`obelisk.idle` payload (ADR-0141).
---@field inhibited boolean Anything is holding the session awake: a logind inhibitor including this shell's own, or the compositor withholding idle notifications (ADR-0160). Either way no threshold event arrives while it is true, so a countdown must stop -- but for different reasons. The logind half is the Supervisor's own gate dropping events; the compositor half is the compositor never sending them, and nothing in this process gates on it.
---@field inhibitors IdleInhibitor[] Idle-inhibitor holders other than this shell. A Wayland holder has an empty `who`, because no protocol names one (ADR-0160).

---@class BluetoothState
---@field available boolean An adapter is bound. `false` means no adapter or no `bluetoothd`, so every other field is inert and every write is a logged no-op.
---@field connected_devices ConnectedDevice[] Paired, connected devices. Unordered: the registry is a `HashMap`, so the order can change on any rebuild. Sort before drawing.
---@field discoverable boolean Other devices can find this adapter and ask to pair; the agent asks the user before any of them does. BlueZ turns it off after `DiscoverableTimeout` (180s by default), and that change reaches this field like any other.
---@field discovered_devices DiscoveredDevice[] Unpaired devices seen by the running scan; empties when discovery stops.
---@field discovering boolean Whether discovery is running, which fills [`BluetoothState::discovered_devices`].
---@field enabled boolean Whether the adapter is powered, so always `false` without one.
---@field paired_devices PairedDevice[] Paired devices that are not connected, unordered like `connected_devices`.
---@field pairing_request? PairingRequest The pairing question on screen, or `nil`. Answer with `bluetooth:answer_pairing(accept)`.

---@class BrightnessState
---`obelisk.brightness`'s full payload (§ 2.3). `percent` is the unchanged `StateSnapshot` JSON
---key. `Default` (`0`) precedes the first read, but no-device construction emits no signal, so
---Lua never observes the placeholder (see `brightness/mod.rs`).
---@field percent integer Screen backlight, `0` to `100`, from sysfs `brightness` (the requested value), not `actual_brightness`, which can lag during a hardware fade.

---@class FilesState
---`obelisk.files`'s payload (ADR-0120): watched folders keyed by the path `watch` was given, so
---`obelisk.files.folders[folder]` reads back with the string the config wrote.
---@field folders table<string, Folder> One entry per active `files:watch(path)`, keyed by `path` with trailing slashes stripped. Absent until watched, so an unrequested folder is not an empty list.

---@class ProcessesState
---`obelisk.processes`'s payload.
---@field sessions table<string, SessionProcess> One entry per name a config declared with `session_process`, keyed by that name. A name nothing declared is absent rather than stopped, so a typo reads `nil` instead of quietly looking like a program that never starts.

---@class KeyboardState
---`obelisk.keyboard`'s combined payload. `backlight_pct` is `-1` without keyboard-backlight
---hardware. Lock booleans have no sentinel: they default and remain `false` if neither evdev nor
---sysfs resolves. `active_layout` is the non-nullable empty-string sentinel; index and count are
---`0` by default (ADR-0034).
---@field active_layout string Layout display name, e.g. `"English (US)"`; empty before the compositor answers.
---@field active_layout_index integer Active layout's 0-based configured-list position, passed to `keyboard:invoke("switch_layout", index)`.
---@field backlight_pct integer Keyboard backlight, `0` to `100`, or `-1` without a backlight device. Check `-1` before drawing a slider.
---@field caps_lock boolean Caps Lock is on.
---@field layout_count integer Configured layout count. Below `2`, `switch_layout` has nothing to change and a layout indicator need not be drawn.
---@field num_lock boolean Num Lock is on.
---@field scroll_lock boolean Scroll Lock is on.

---@class LockState
---`obelisk.lock`'s payload (ADR-0052 decision 4). `attempts` counts failed authentications since
---acquisition. Lua cannot rebuild it from layout-time state (ADR-0044), so identical failures
---leave one `error` string; empty `error` means no failure, like `keyboard.active_layout`.
---@field active boolean The Renderer confirmed the session locked. A requested but unconfirmed lock remains `false`; [`apply`] changes this only from the Renderer report.
---@field attempts integer PAM answers against the held lock, including success. Resets to `0` only on a new confirmed lock, so it is per-acquisition, not per-failure; lockout rules read it with `error`.
---@field authenticating boolean A password is with PAM and unanswered. `pam_unix` takes about a second, so this drives a spinner; `lock:authenticate` is refused while true.
---@field error string Drawable reason for the last failure, e.g. `"too many attempts"`. Empty before attempts or after success; rewritten on every PAM answer and cleared on a new lock.
---@field unlocking boolean PAM has said yes and the lock is still on the glass, which is the window a config animates its lock screen out in (ADR-0190). True between a successful password and the Renderer's `Unlocked` report. With no `unlock_animation` configured that window is as short as the round trip; with one it is at least that long. Nothing a config does can extend it: the release is scheduled by the Supervisor the moment PAM answers, and this is a readout of that, not a handle on it.

---@class MprisState
---@field players PlayerState[] Every MPRIS player, longest-running first. New players append and position updates do not move entries, so `players[1]` keeps its meaning. Empty when no player is running, which is valid, not an error.

---@class NetworkState
---`obelisk.network`'s live §2.5 state, not only §4.2's scan results. Every field is re-derived from
---NetworkManager on each [`NetworkSignal`] (ADR-0029: no debounce or incremental state).
---
---The AP list cannot answer "am I online": it has no wired link and cannot distinguish a powered
---down radio from a powered radio with no association.
---@field available_networks AccessPointInfo[] Last completed scan: SSID-deduplicated, connected first, then strongest, capped at 20. Kept while [`NetworkState::scanning`] is true so the panel does not blank; payload order is ready to draw.
---@field connect_error? string Display text for the last failed `network:connect`, or `nil` after success or before any attempt. `AddAndActivateConnection2` returns before the radio tries; this is filled later from the activation's `StateChanged(state, reason)`, where a wrong password is knowable. Sticky until the next attempt, like `UpdatesState::check_error`.
---@field connected boolean A connection carries the default route, from `PrimaryConnection` (§2.5). `/` means none, hence offline.
---@field connecting_ssid? string SSID that `network:connect` is joining, or `nil`. Names the row whose spinner runs and clears when the attempt reaches either verdict.
---@field ethernet_enabled boolean A wired device is activated. This is the setter's read-back; carrier stays up when a cable is seated, so it would not reflect `network:set_ethernet_enabled(false)`.
---@field ethernet_ip? string The first activated wired device's IPv4 address without its prefix, or `nil`.
---@field ethernet_present boolean At least one wired device exists, cable or not.
---@field ethernet_speed integer Link speed in Mb/s of the wired device `ethernet_ip` describes, or `0` when unknown or no wired link is activated.
---@field networking_enabled boolean Whether NetworkManager manages networking, from `NetworkingEnabled`. `false` means the other fields describe a switched-off stack.
---@field password_ssid? string SSID whose `network:connect` waits for a password, or `nil`. Set by [`resolve_connect_intent`](NetworkController::resolve_connect_intent) when no saved profile or open AP answers, and after NetworkManager rejects a key; cleared by the consuming attempt or `network:cancel_connect`. Kept here because "no profile for this SSID" lives in NetworkManager, not config (ADR-0037). The shell binds `keyboard_interactivity` to it, so focus lasts exactly while it names a network.
---@field scanning boolean A scan is in flight. Set when `network:scan()` is accepted, before NetworkManager confirms, so the spinner starts on the click.
---@field ssid? string Wi-Fi SSID, `"Ethernet"` for a wired default route, or `nil` with no association. Wired wins when both are up. An association negotiating DHCP has an `ssid` but `connected == false`.
---@field strength integer Associated AP strength, `0` to `100`, or `0` without Wi-Fi association. Read from the merged entry the panel draws, so the bar and list agree.
---@field wifi_enabled boolean Wi-Fi radio power, from `WirelessEnabled`; distinguishes radio-off from radio-on with no association.
---@field wifi_ip? string The Wi-Fi device's IPv4 address without its prefix, or `nil` while it holds none.
---@field wifi_present boolean A Wi-Fi device exists. `wifi_enabled` alone cannot say so, because NetworkManager reports the radio switch with no hardware behind it.

---@class NotificationsState
---`notifications.feed`/`notifications.dnd` `StateSnapshot` payload (ADR-0033).
---@field dnd boolean DND from `notifications:set_dnd`; gates only non-critical sounds. Notifications remain accepted, queued, and in `feed`; popup suppression is config policy.
---@field feed Notification[] Newest 20 first, including unread retired entries until dismissed (ADR-0100); `expired` distinguishes them. This is a view of the 100-entry queue, so older entries remain dismissable by id after leaving the list (ADR-0033).

---@class PowerState
---`obelisk.power`'s full payload (§ 2.13). Optional fields are omitted from JSON, so unavailable
---host data reads as Lua `nil`; see `power/mod.rs` for the four-field split.
---@field active_profile? string Active platform profile, e.g. `"balanced"`, set by `power:set_profile`; `nil` without power-profiles-daemon.
---@field energy_rate? number UPower's `EnergyRate` in watts, unchanged. It is positive in both directions, so [`PowerState::on_battery`] supplies the sign; `nil` without UPower.
---@field on_battery? boolean Running on battery rather than mains, from UPower; `nil` without UPower. This is the mains question; charge direction is `obelisk.battery.state`.
---@field profiles? string[] Profiles in daemon order, e.g. `{"performance", "balanced", "power-saver"}`; `nil` when power-profiles-daemon is absent. Drive selectors from this list because machines differ.

---@class PrivacyState
---@field camera_users PrivacyUser[] Processes holding a camera open. Empty means no camera is in use; a config draws its indicator only when this is non-empty.
---@field microphone_users PrivacyUser[] Apps PipeWire reports reading a microphone now (ADR-0137). Open-but-idle streams are absent: this means "something is listening", not "something could". Distinct from `obelisk.audio.source_muted`, a device setting; a muted active capture appears in both.
---@field screencast_users PrivacyUser[] Apps producing PipeWire screen-capture streams (ADR-0137). Names may be the portal's identity for portal-created nodes. wlr-screencopy recorders (`wf-recorder`, `grim`) bypass PipeWire and never appear.

---@class SysinfoState
---`obelisk.sysinfo`'s five Lua-visible fields (docs/lua-api.md §2.12), with field
---names unchanged from the `StateSnapshot` JSON keys.
---@field cpu_percent integer Total CPU utilization, `0` to `100`, across cores. `0` before two samples can form a delta.
---@field ram_percent integer Physical memory in use, `0` to `100`.
---@field swap_percent integer Swap in use, `0` to `100`; `0` means either no swap or empty swap.
---@field temp_cores integer[] Per-core Celsius temperatures from one hwmon pass. Empty when none are exposed. Length is sensor count, not core count, in hwmon order.
---@field temp_gpu integer GPU temperature in Celsius, or `-1` without a GPU sensor. Read in the same hwmon pass as [`SysinfoState::temp_cores`], so neither is newer than the other.

---@class SystemState
---`obelisk.system`'s Lua-visible fields (docs/lua-api.md §2.11), with their
---`StateSnapshot` JSON keys unchanged.
---@field monotonic integer Whole seconds since this controller was built, which is the first time a config asked for `system`. Only a difference means anything; take durations from this rather than from `time`, which `settimeofday` and an NTP step move underneath a deadline. ponytail: `Instant` is `CLOCK_MONOTONIC` on Linux, so a suspend does not count toward an elapsed reading. Suspend-inclusive timing wants `CLOCK_BOOTTIME` as a second field.
---@field time integer Unix epoch seconds, not milliseconds. §2.11 omits the unit, but `os.date` expects seconds; milliseconds would be wrong by 1000x.

---@class StorageState
---`obelisk.storage`'s payload (ADR-0136).
---@field files table<string, any> One entry per declared `persistent_table`, keyed by the absolute `path` joined from `path` and `name`. Absent until declared, so unopened files read as `nil`, not an empty table.

---@class PolkitState
---`obelisk.polkit`'s payload. All fields except `active` are empty while it is false.
---@field action_id string Action being authorized, e.g. `org.freedesktop.systemd1.manage-units`.
---@field active boolean polkitd is waiting for the user; the remaining fields describe its request.
---@field authenticating boolean A password is with PAM and unanswered. `pam_unix` takes about a second, so this drives a checking line; a second submit is refused while true.
---@field error string Drawable reason for the last failure, e.g. `"authentication failed"`. Empty until failure; the prompt stays open for another try and clears with it.
---@field icon_name string Themed icon name, or empty when the caller set none.
---@field message string Translated text polkitd wants shown, such as "Authentication is required to ...".

---@class TrayState
---@field items TrayItem[] Registered items, oldest first. New items append; property updates do not move them, so no sorting is needed. Registration order avoids lexicographic D-Bus id order, where `1.100` precedes `1.20` and a new app lands mid-strip.

---@class UpdatesState
---`obelisk.updates` payload. `check_error`/`install_error` are `None` when clear. While
---`installing`, `install_total_steps == 0` means the manager has not printed the transaction size.
---@field check_error? string Last check error, or `nil` after success. Checks never modify the system (`Backend::check`), so this is a network/parse failure, not a half-applied change.
---@field checking boolean A check is running. Set before sync and cleared when its result is written, with a push at both edges for spinners/refresh controls. `updates:check` refuses a second check while true.
---@field consecutive_check_failures integer Consecutive check failures, reset to `0` by the first success. Thresholds belong in config.
---@field count integer Number of packages with newer synced-repo versions. Always `#packages`, duplicated so a badge need not walk the list.
---@field install_current_package string Current package name from the step line. Empty before the first line, never `nil`.
---@field install_current_step integer Current package number, using the manager's 1-based `(2/5)` counter. `0` before progress.
---@field install_error? string Why Supervisor never got a manager answer: spawn or wait failed. Unlike [`UpdatesState::install_exit_code`], this means the install was never answered and the failure is Supervisor's.
---@field install_exit_code? integer Manager exit code from the last install: `0` success, its code on failure, `nil` before one finishes. Together with [`UpdatesState::install_log`], it is the failure fact; wording such as network, disk, or signature error belongs in config (ADR-0113 amendment).
---@field install_finished_at? integer Unix seconds when the last install stopped, regardless of outcome. Use it with the caller's install start to measure duration.
---@field install_log string[] Last install output, newest last, stdout/stderr interleaved by arrival (two readers make the cross-stream order inexact). Keeps the last 200 lines; cleared when an install starts.
---@field install_total_steps integer Transaction package count. `0` while [`UpdatesState::installing`] means no step line yet; show progress as indeterminate rather than divide.
---@field installing boolean An install is running. `install_*` describe a started run; `updates:install` refuses a second one while true.
---@field last_successful_check? integer Unix seconds when the last check completed successfully, or `nil` this session. Failed checks preserve the older value.
---@field package_manager? string Package manager name, or `nil` when unsupported. Available before any check and used by an indicator to decide whether it belongs on the bar (ADR-0134), e.g. `"pacman"`.
---@field packages UpdateCandidate[] Packages that would upgrade, one per entry. A failed check preserves the last good list and [`UpdatesState::count`] while [`UpdatesState::check_error`] reports the gap.
---@field reboot_required boolean Whether `/run/obelisk-shell-reboot-required` exists. A pacman hook writes it, so a terminal upgrade raises it too, and `/run` being tmpfs means a boot clears it. Nothing in Obelisk writes or clears it.

---@class WorkspacesState
---`obelisk.workspaces` payload (§ 2.9). Field names are JSON keys; absent `active_client` is
---omitted, not `null` (§ 2.9 says `nil` when unfocused).
---@field active_client? ActiveClient Focused toplevel, or `nil` if none. One window per session, not per output; an unfocused monitor cannot be queried (ADR-0056 decision 4).
---@field compositor string Source compositor, `"niri"` or `"hyprland"` (ADR-0119). Hyprland creates a numbered workspace on focus, so strips pad empty slots there; niri keeps its trailing empty one.
---@field outputs OutputWorkspaces[] One entry per output, keyed by connector name; empty until the first compositor answer.
---@field special? SpecialWorkspace[] Compositor special workspaces, Hyprland's scratchpads, ordered by name (ADR-0119). Absent when unsupported (`special == nil`); an empty list means supported but none exist. Hyprland lists a special only while it holds a window or is shown.

--- Capabilities -------------------------------------------------------------------------------

---@class ApplicationsCapability: Capability<ApplicationsState>
---@field invoke fun(self: ApplicationsCapability, command: "refresh"|"launch"|"open_url", ...: any)

---@class AudioCapability: Capability<AudioState>
local AudioCapability = {}

---@class BatteryCapability: Capability<BatteryState>
local BatteryCapability = {}

---@class IdleCapability: Capability<IdleState>
---@field invoke fun(self: IdleCapability, command: "register"|"inhibit"|"release_inhibit", ...: any)
---@field register_threshold fun(self: IdleCapability, seconds: integer, on_idle: fun(), on_resume: fun()) Runs `on_idle` after `seconds` without input on the seat, and `on_resume` when input returns. Registrations do not survive a config reload, so register at the top level rather than inside a callback that fires more than once.
---@field inhibit fun(self: IdleCapability, reason: string) Holds off idle actions system-wide (logind `Inhibit`, `what="idle"`) until a matching `release_inhibit`. Counted, so two holders need two releases. While any hold is out -- this one or another application's -- no threshold fires and `inhibited` says so.
---@field release_inhibit fun(self: IdleCapability) Releases one `inhibit` hold. A release with no matching `inhibit` is a no-op.

---@class BluetoothCapability: Capability<BluetoothState>
---@field invoke fun(self: BluetoothCapability, command: "set_enabled"|"set_discoverable"|"start_discovery"|"stop_discovery"|"pair"|"connect"|"disconnect"|"forget"|"answer_pairing", ...: any)

---@class BrightnessCapability: Capability<BrightnessState>
---@field invoke fun(self: BrightnessCapability, command: "set", ...: any)

---@class FilesCapability: Capability<FilesState>
---@field invoke fun(self: FilesCapability, command: "watch"|"unwatch", ...: any)

---@class ProcessesCapability: Capability<ProcessesState>
---@field invoke fun(self: ProcessesCapability, command: "declare"|"start"|"signal"|"stop", ...: any)

---@class KeyboardCapability: Capability<KeyboardState>
---@field invoke fun(self: KeyboardCapability, command: "set_backlight"|"switch_layout", ...: any)

---@class LockCapability: Capability<LockState>
local LockCapability = {}

---@class MprisCapability: Capability<MprisState>
---@field invoke fun(self: MprisCapability, command: "control"|"seek"|"seek_relative", ...: any)

---@class NetworkCapability: Capability<NetworkState>
---@field invoke fun(self: NetworkCapability, command: "set_networking_enabled"|"set_wifi_enabled"|"set_ethernet_enabled"|"scan"|"connect"|"cancel_connect"|"abort_connect"|"forget"|"disconnect_wifi", ...: any)

---@class NotificationsCapability: Capability<NotificationsState>
local NotificationsCapability = {}

---@class PowerCapability: Capability<PowerState>
---@field invoke fun(self: PowerCapability, command: "set_profile", ...: any)

---@class PrivacyCapability: Capability<PrivacyState>
local PrivacyCapability = {}

---@class SysinfoCapability: Capability<SysinfoState>
---@field invoke fun(self: SysinfoCapability, command: "configure", ...: any)

---@class SystemCapability: Capability<SystemState>
local SystemCapability = {}

---@class StorageCapability: Capability<StorageState>
---@field invoke fun(self: StorageCapability, command: "open"|"set", ...: any)

---@class PolkitCapability: Capability<PolkitState>
---@field invoke fun(self: PolkitCapability, command: "cancel", ...: any)

---@class TrayCapability: Capability<TrayState>
---@field invoke fun(self: TrayCapability, command: "activate"|"secondary_activate"|"scroll"|"activate_menu_item"|"menu_will_show", ...: any)

---@class UpdatesCapability: Capability<UpdatesState>
---@field invoke fun(self: UpdatesCapability, command: "check"|"configure"|"install", ...: any)

---@class WorkspacesCapability: Capability<WorkspacesState>
---@field invoke fun(self: WorkspacesCapability, command: "focus"|"toggle_special", ...: any)

--- Off-roster members ---------------------------------------------------------------------------
-- Not capabilities and not in `shared::Capability::ALL`, so they have no payload struct to derive
-- from and are written by hand: `Screen` and `RescueState` come from the renderer's own state.
--
-- `obelisk.idle` used to be here too. It joined the roster with ADR-0141, because there turned out
-- to be idle state worth reading after all -- whether anything is holding the session awake, and
-- which application it is. It is the one member that is both: `IdleCapability` above is generated
-- from `IdleState` like any other, and the three methods below are declared onto it by hand,
-- because their callbacks are Lua values that never cross the wire and so have no action schema to
-- derive from.

---@class Screen
---@field name string The connector name, e.g. `"eDP-1"`. What a surface's `monitor` takes, and what an `obelisk.workspaces` output entry is keyed by.
---@field width integer Logical pixels, already divided by `scale`. Not the mode's pixel count.
---@field height integer Logical pixels, on the same terms as `width`.
---@field scale integer The compositor's integer scale factor for this output, `1` on an ordinary display and `2` on a HiDPI one. Not a divisor: `width` and `height` above are already logical. Read it to pick sizes, the way `theme.s(hidpi, normal)` does.
---@field refresh number Hz. `0` for an output with no current mode, such as a virtual one.

---@class RescueState
---@field is_rescue boolean A reload failed and the scene from before the edit is still on screen. Covers reloads only: a config that fails its very first evaluation has no tree to render a banner through (ADR-0046).
---@field error_log string The Lua error that caused it, ready to draw. Empty while `is_rescue` is false.

---@class ObeliskVersion
---@field major integer Breaking IDL changes.
---@field minor integer Bumped for an IDL field added or changed, which is what `obelisk.version.minor >= n` gates on.
---@field patch integer Everything else. Never affects what a config may use.

---@class Obelisk
---@field audio AudioCapability PipeWire: master volume and mute, the output and input device lists, and one entry per application currently playing.
---@field network NetworkCapability NetworkManager: scan state and the access points the last scan found. Connecting is a command, not a field.
---@field bluetooth BluetoothCapability BlueZ: adapter power, discovery state, and the connected and discovered device lists.
---@field tray TrayCapability StatusNotifierItem: every registered tray icon with its artwork, status and DBusMenu tree.
---@field notifications NotificationsCapability The freedesktop notification server: the newest 20 live notifications and the do-not-disturb toggle.
---@field mpris MprisCapability MPRIS: every media player on the bus, with track metadata, playback state and a position to extrapolate from.
---@field sysinfo SysinfoCapability CPU, memory and swap load, plus hwmon temperatures. Sampled on a timer this capability owns.
---@field keyboard KeyboardCapability Lock-key state, the active layout, and the keyboard backlight where the machine has one.
---@field privacy PrivacyCapability Who is using the camera, the microphone, or the screen right now. Empty means nobody is.
---@field updates UpdatesCapability Pending pacman upgrades, the progress of an install in flight, and whether the kernel changed under you.
---@field lock LockCapability The session lock: whether it is held, whether a password is with PAM, and why the last attempt failed.
---@field polkit PolkitCapability The authentication request polkitd is waiting on: what for, whether a password is with PAM, and why the last attempt failed.
---@field battery BatteryCapability UPower's display device: charge, what the battery is doing, and the time estimates when it has them.
---@field system SystemCapability A clock that ticks once a second.
---@field brightness BrightnessCapability The screen backlight, as a percentage.
---@field workspaces WorkspacesCapability The compositor's workspaces per output, and the focused toplevel window.
---@field power PowerCapability power-profiles-daemon's platform profiles, plus whether you are on mains and how many watts are moving.
---@field applications ApplicationsCapability The installed desktop entries, listed and indexed by the `app_id` a window reports.
---@field files FilesCapability The files in each folder a config asked to watch, kept current through inotify.
---@field storage StorageCapability Every JSON file a config declared with `persistent_table`, keyed by its absolute path.
---@field idle IdleCapability Whether anything is holding the session awake, and which application it is. Its thresholds and the inhibit pair are methods on the same member.
---@field processes ProcessesCapability Every long-running program a config declared with `session_process`: whether it is up, since when, and how the last run ended.
---@field screens Signal<Screen[]> Renderer-sourced, seeded to an empty list, and the one signal with a value at first evaluation (ADR-0041).
---@field rescue Signal<RescueState> Renderer-sourced, no commands (ADR-0046).
---@field version ObeliskVersion Three integers a config can compare. Not a signal.
---@field config_dir string The directory `shell.lua` was loaded from, so a config can name a file it ships beside itself. Not a signal.
obelisk = {}
