---@meta
-- GENERATED by `supervisor/src/stubs.rs` for oblisk 0.1.0. Do not edit: run
-- `UPDATE_STUBS=1 cargo test -p supervisor stubs` and commit what changes.
--
-- The version above is what `stub_version` reads. Stubs describing a different engine than the one
-- installed are worse than no stubs, because they are wrong with authority, so `oblisk init` says
-- so and refreshes them.
--
-- The capability classes below are the supervisor's own `Serialize` types, which is what
-- `push_snapshot` sends, so a field here is a field that crosses the socket. Descriptions are the
-- Rust doc comments on those fields. To document a field for config authors, write the doc comment
-- in Rust and regenerate.
--
-- A capability reads `nil` until its first `StateSnapshot` arrives, which every config sees on
-- every boot. A signal resolving to `nil` means the property is absent, so a bound node renders its
-- default rather than failing the tree (ADR-0044). A JSON `null` arrives as an absent key rather
-- than a sentinel (ADR-0057), so `if item.icon_path then` is the right guard for an optional field.

---@class Capability: Signal
---A capability is a signal you can also command. `:get()` and `:map()` read the pushed payload;
---`:invoke()` sends a command the supervisor dispatches. Read-only otherwise: `:set()` refuses it,
---or a config could overwrite the SSID the supervisor just pushed.
local Capability = {}

---@param command string
---@param ... any
function Capability:invoke(command, ...) end

--- Payload types ------------------------------------------------------------------------------

---@class AccessPointInfo
---One scanned access point, already resolved to what `network.available_networks` needs
---(docs/oblisk-idl-api-specs.md §2.5). `Serialize`: this is what ends up in a `StateSnapshot`'s
---`payload`, same convention as `audio::mixer::AppStream`.
---@field active boolean
---@field band string
---@field secure boolean
---@field ssid string
---@field strength integer

---@class ActiveClient
---§ 2.9's `active_client`, minus `is_fullscreen` (docs/adr/0056 decision 5: niri-ipc 26.4.0's
---`Window` has no such field, and a fabricated `false` would be wrong for fullscreen windows).
---`class` is niri's `app_id`: X11's `WM_CLASS` has no Wayland equivalent.
---@field class string
---@field is_floating boolean
---@field title string

---@class AppStream
---One playback stream node PipeWire has advertised, filtered to
---`media.class == "Stream/Output/Audio"` and resolved to its owning process.
---
---`Serialize`: this is what `main.rs` puts in a `StateSnapshot`'s `payload`, pushed to the
---Renderer over the control socket as-is. Field names match § 2.4's spelling (`id`, `name`,
---docs/adr/0053 decision 3). `pid`/`process_name` are kept even though § 2.4 doesn't list them
----- docs/adr/0016 exists because finding the owning process was genuinely hard, and discarding
---that answer would throw away the one part of this payload that took real work.
---@field id integer PipeWire registry id of the stream node -- the key [`AudioApps`] tracks entries by.
---@field muted boolean § 2.4's per-app mute, from the same `Props` param as `volume`.
---@field name? string `application.name`, if the client set one.
---@field pid integer `application.process.id`: the pid PipeWire recorded for the stream's owning process.
---@field process_name? string `/proc/{pid}/comm` for `pid`, if the process still existed when this stream was seen.
---@field volume number § 2.4's per-app volume, range `[0.0, 1.0]`. Read from this stream node's own `SPA_PARAM_Props` through the same cube-root conversion the master sink uses (see [`master`]): a stream stores `channelVolumes` cubed exactly as a sink does, confirmed with `pw-cli enum-params <id> Props` against a live playback stream. `1.0` until that param arrives, PipeWire's own untouched value for a stream never adjusted.

---@class AppSummary
---One application as the config sees it (docs/adr/0061). Deliberately the display half only:
---the argv never crosses into Lua, because `applications:launch(id)` is what runs it and a
---config that could rewrite a command line before it ran would be a config that could be made
---to run something else.
---@field icon? string The `Icon=` key as written: a theme name, or an absolute path. `icon { name = ... }` takes either, which is exactly what ADR-0054 decision 2 built it for. `None` for an entry with no `Icon=` at all, so a config can tell "no icon" from an icon that failed to resolve.
---@field id string The desktop file id (`org.telegram.desktop`), and `launch`'s one argument.
---@field name string

---@class AudioDevice
---One § 2.4 `sinks`/`sources` entry. Both arrays are the same three fields, so they are the
---same type: an output and an input differ in which `media.class` produced them and in
---nothing a config reads.
---
---`name` is § 2.4's "user-friendly description", which is `node.description` (`"Built-in Audio
---Analog Stereo"`), not the `node.name` the metadata keys route by
---(`"alsa_output.pci-0000_00_1f.3.analog-stereo"`). Both exist on every device this machine
---advertises, and only one is meant for a person.
---@field active boolean Whether this is the device the `default.audio.sink`/`default.audio.source` metadata key currently routes to.
---@field id integer PipeWire registry id, which is what `audio:set_default_sink(id)` takes.
---@field name string

---@class CameraUser
---One active camera user (ADR-0034: `privacy.camera_users: table`, array of `{app_name}`,
---empty = inactive).
---@field app_name string

---@class ConnectedDevice
---@field battery integer `-1` if unsupported/unknown (no `Battery1` interface on this device, or its `Percentage` property failed to read) -- per the IDL comment, not a sentinel invented here.
---@field category string
---@field codec? string Always `None` this round -- codec query/control is deferred (ADR-0030): it needs a live PipeWire `Device` proxy, an `audio`-capability concern, not `bluetooth`'s.
---@field mac string
---@field name string

---@class DiscoveredDevice
---@field mac string
---@field name string
---@field paired boolean Always `false` -- per the IDL comment, every entry in this pool is by definition unpaired.

---@class MenuItem
---One node of a DBusMenu layout tree, already resolved into what `tray.items[].menu` needs
---(docs/oblisk-idl-api-specs.md §2.14).
---@field children MenuItem[]
---@field enabled boolean
---@field icon_name? string
---@field id integer
---@field label? string
---@field menu_type string
---@field toggle_state? integer
---@field toggle_type? string

---@class Notification
---One queued notification -- `notifications.feed[]`'s object shape (docs/oblisk-idl-api-specs.md
---§2.7, ADR-0033's corrections: `body` is a span array not a flat string, `urgency`/`has_reply`
---are new fields). Trimmed to what the feed shape and write commands need -- the raw `actions`
---array is never stored, only the `has_reply` bool it collapses into.
---@field app_name string
---@field body NotificationSpan[]
---@field has_reply boolean
---@field icon_path? string
---@field id integer
---@field summary string
---@field urgency Urgency

---@class NotificationSpan
---One allowlisted body-markup run (CONTEXT.md's "Notification body span"; ADR-0033). A text run
---carries its own styling and, for a `<a href>`, the link target; an image run carries only a
---spooled/validated path -- `alt` text is parsed for grammar completeness but not carried
---forward, since nothing in this round's scope reads it.
---@field bold? boolean
---@field href? string
---@field image_path? string
---@field italic? boolean
---@field kind "text"|"image"
---@field text? string
---@field underline? boolean

---@class OutputWorkspaces
---One output's workspace state. `workspaces` is docs/adr/0056 decision 3's addition to
---§ 2.9.
---@field active_workspace integer
---@field focused_workspace? integer docs/adr/0056 decision 4: present only on the output that actually holds focus, so `out.focused_workspace ~= nil` is the "is this the focused monitor" test.
---@field name string
---@field workspaces WorkspaceEntry[]

---@class PlayerState
---@field album_art_path string
---@field artist string
---@field id string
---@field identity string
---@field length integer `-1` when `mpris:length` is absent/malformed (a live stream, or a player that simply doesn't report it) -- a genuine unavailable, not a fabricated zero (ADR-0036).
---@field play_state string
---@field position integer
---@field position_updated_at integer
---@field title string

---@class TrayItem
---@field icon_name? string
---@field icon_path? string
---@field id string
---@field item_is_menu boolean
---@field menu? MenuItem[]
---@field name string
---@field status string
---@field tooltip? string

---@class UpdateCandidate
---One installed package with a newer version in some sync repo.
---@field download_size integer
---@field installed_size integer
---@field name string
---@field new_version string
---@field old_version string

---@alias Urgency "low"|"normal"|"critical"
---The `low`/`normal`/`critical` tier (CONTEXT.md's "Notification urgency"). `Hash`/`Eq` so it can
---key the sound registry directly.

---@class WorkspaceEntry
---`id` is niri's stable, monitor-independent identity: what `active_workspace`/
---`focused_workspace` refer to and what `workspaces:focus(id)` takes. `idx` is the 1-based
---position on that output (what a keybind/button label means), not stable across a reorder.
---@field id integer
---@field idx integer
---@field name? string

---@class ApplicationsState
---`oblisk.applications`'s payload (docs/adr/0061 decision 2).
---
---`by_app_id` repeats the summaries in `entries` rather than indexing into it. An index would
---have to be a Lua array index, and Lua counts from one while the JSON array this serializes to
---counts from zero, so every config reading it would carry an off-by-one nobody can see in the
---payload. Repeating three small fields for a few hundred entries costs less than that trap.
---@field by_app_id table<string, AppSummary>
---@field entries AppSummary[]

---@class AudioState
---The full `oblisk.audio` payload (§ 2.4, docs/adr/0053 decision 3): master output
---volume/mute plus the per-app stream list.
---@field apps AppStream[]
---@field muted boolean Master output mute.
---@field sinks AudioDevice[]
---@field sources AudioDevice[]
---@field volume number Master output volume, range `[0.0, 1.0]` -- see [`master`]'s module doc comment for how this is derived from the default sink's `channelVolumes`.

---@class BatteryState
---`oblisk.battery`'s full payload (§ 2.2). Field names are the `StateSnapshot` JSON keys
---verbatim -- may not be renamed. `Default` (`false`, `0`, `false`) is itself the correct
---"no battery hardware" answer for a desktop, not a placeholder needing a sentinel.
---@field charging boolean
---@field percent integer
---@field present boolean

---@class BluetoothState
---@field connected_devices ConnectedDevice[]
---@field discovered_devices DiscoveredDevice[]
---@field discovering boolean
---@field enabled boolean

---@class BrightnessState
---`oblisk.brightness`'s full payload (§ 2.3). `percent` is the JSON key verbatim -- the
---Renderer routes it into the Lua `oblisk.brightness` signal table by name, unchanged.
---`Default` (`0`) is a placeholder before the first real read; never observed if no device
---was found, since no signal is sent in that case (see `brightness/mod.rs`).
---@field percent integer

---@class KeyboardState
---`oblisk.keyboard`'s combined payload. `backlight_pct` is `-1` when this machine has no
---keyboard-backlight hardware. `caps_lock`/`num_lock`/`scroll_lock` have no sentinel (bare
---`bool`) -- they default `false` and stay there, logged once, if neither evdev nor sysfs
---resolves. `active_layout` defaults to an empty string (IDL declares it non-nullable,
---ADR-0034), `active_layout_index`/`layout_count` default `0`.
---@field active_layout string
---@field active_layout_index integer
---@field backlight_pct integer
---@field caps_lock boolean
---@field layout_count integer
---@field num_lock boolean
---@field scroll_lock boolean

---@class LockState
---`oblisk.lock`'s payload (docs/adr/0052 decision 4). `attempts` counts failed authentications
---since acquisition, and exists because Lua can't rebuild it: capability state is sampled at
---layout time (docs/adr/0044), not evented, so two identical consecutive failures are one
---unchanged `error` string. `error`'s "nothing went wrong" value is the empty string, the same
---convention `keyboard`'s `active_layout` uses.
---@field active boolean
---@field attempts integer
---@field authenticating boolean
---@field error string

---@class MprisState
---@field players PlayerState[]

---@class NetworkState
---`oblisk.network`'s live push state (docs/adr/0029). Scoped to exactly what §4.2 asks for --
---scanning status and the deduplicated AP list -- not the full §2.5 read schema
---(`connected`/`ssid`/`wifi_enabled`/etc.), which §4 doesn't ask this controller to track.
---@field available_networks AccessPointInfo[]
---@field scanning boolean

---@class NotificationsState
---`notifications.feed`/`notifications.dnd`'s `StateSnapshot` payload shape (ADR-0033).
---@field dnd boolean
---@field feed Notification[]

---@class PowerState
---`oblisk.power`'s full payload (§ 2.13). Every field is `Option`, omitted from the JSON
---rather than serialized as `null`, so a config reads `nil` for anything this host cannot
---answer. See `power/mod.rs` for why this is four optional fields, not one on/off capability.
---@field active_profile? string
---@field energy_rate? number
---@field on_battery? boolean
---@field profiles? string[]

---@class PrivacyState
---@field camera_users CameraUser[]

---@class SysinfoState
---`oblisk.sysinfo`'s five Lua-visible fields (docs/oblisk-idl-api-specs.md §2.12). Field
---names are the `StateSnapshot` payload's JSON keys verbatim -- the Renderer routes them
---straight into the Lua signal table by name, unchanged.
---@field cpu_percent integer
---@field ram_percent integer
---@field swap_percent integer
---@field temp_cores integer[]
---@field temp_gpu integer

---@class SystemState
---`oblisk.system`'s two Lua-visible fields (docs/oblisk-idl-api-specs.md §2.11). Field names
---are the `StateSnapshot` payload's JSON keys verbatim.
---@field state any The parsed contents of `state.json`, or an empty object -- see `state::load_state`. Read-only from Lua's side: `system:write_state` (§3.2) is a separate, unbuilt write path.
---@field time integer Unix epoch seconds, not milliseconds -- §2.11 calls it "system time epoch" with no unit stated. `os.date` wants seconds, so a millis reading would be silently wrong by 1000x.

---@class TrayState
---@field items TrayItem[]

---@class UpdatesState
---`oblisk.updates`'s combined payload. `check_error`/`install_error` are `None` when
---nothing's gone wrong, not a fabricated empty string. `install_total_steps == 0` while
---`installing` is true means the transaction size isn't known yet (pacman hasn't printed it).
---@field check_error? string
---@field count integer
---@field install_current_package string
---@field install_current_step integer
---@field install_error? string
---@field install_total_steps integer
---@field installing boolean
---@field last_successful_check? integer
---@field packages UpdateCandidate[]
---@field reboot_required boolean

---@class WorkspacesState
---`oblisk.workspaces`'s full payload (§ 2.9). Field names are the JSON keys verbatim.
---`active_client` is `Option` (§ 2.9: "or `nil` if none focused"), omitted rather than
---serialized as `null`.
---@field active_client? ActiveClient
---@field outputs OutputWorkspaces[]

--- Capabilities -------------------------------------------------------------------------------

---@class ApplicationsCapability: Capability
local ApplicationsCapability = {}
---@return ApplicationsState
function ApplicationsCapability:get() end
---@param fn fun(value: ApplicationsState): any
---@return Signal
function ApplicationsCapability:map(fn) end
---@param command "refresh"|"launch"
---@param ... any
function ApplicationsCapability:invoke(command, ...) end

---@class AudioCapability: Capability
local AudioCapability = {}
---@return AudioState
function AudioCapability:get() end
---@param fn fun(value: AudioState): any
---@return Signal
function AudioCapability:map(fn) end
---@param command "set_volume"|"set_muted"|"toggle_mute"|"set_default_sink"|"set_default_source"|"set_app_volume"|"set_app_muted"
---@param ... any
function AudioCapability:invoke(command, ...) end

---@class BatteryCapability: Capability
local BatteryCapability = {}
---@return BatteryState
function BatteryCapability:get() end
---@param fn fun(value: BatteryState): any
---@return Signal
function BatteryCapability:map(fn) end

---@class BluetoothCapability: Capability
local BluetoothCapability = {}
---@return BluetoothState
function BluetoothCapability:get() end
---@param fn fun(value: BluetoothState): any
---@return Signal
function BluetoothCapability:map(fn) end
---@param command "set_enabled"|"start_discovery"|"stop_discovery"|"connect"|"disconnect"|"pair"|"forget"
---@param ... any
function BluetoothCapability:invoke(command, ...) end

---@class BrightnessCapability: Capability
local BrightnessCapability = {}
---@return BrightnessState
function BrightnessCapability:get() end
---@param fn fun(value: BrightnessState): any
---@return Signal
function BrightnessCapability:map(fn) end
---@param command "set"
---@param ... any
function BrightnessCapability:invoke(command, ...) end

---@class KeyboardCapability: Capability
local KeyboardCapability = {}
---@return KeyboardState
function KeyboardCapability:get() end
---@param fn fun(value: KeyboardState): any
---@return Signal
function KeyboardCapability:map(fn) end
---@param command "set_backlight"|"switch_layout"
---@param ... any
function KeyboardCapability:invoke(command, ...) end

---@class LockCapability: Capability
local LockCapability = {}
---@return LockState
function LockCapability:get() end
---@param fn fun(value: LockState): any
---@return Signal
function LockCapability:map(fn) end
---@param command "lock"
---@param ... any
function LockCapability:invoke(command, ...) end

---@class MprisCapability: Capability
local MprisCapability = {}
---@return MprisState
function MprisCapability:get() end
---@param fn fun(value: MprisState): any
---@return Signal
function MprisCapability:map(fn) end
---@param command "control"|"seek"|"seek_relative"
---@param ... any
function MprisCapability:invoke(command, ...) end

---@class NetworkCapability: Capability
local NetworkCapability = {}
---@return NetworkState
function NetworkCapability:get() end
---@param fn fun(value: NetworkState): any
---@return Signal
function NetworkCapability:map(fn) end
---@param command "scan"|"connect"|"forget"|"set_wifi_enabled"|"set_ethernet_enabled"|"set_networking_enabled"
---@param ... any
function NetworkCapability:invoke(command, ...) end

---@class NotificationsCapability: Capability
local NotificationsCapability = {}
---@return NotificationsState
function NotificationsCapability:get() end
---@param fn fun(value: NotificationsState): any
---@return Signal
function NotificationsCapability:map(fn) end
---@param command "dismiss"|"reply"|"set_sound"|"set_dnd"
---@param ... any
function NotificationsCapability:invoke(command, ...) end

---@class PowerCapability: Capability
local PowerCapability = {}
---@return PowerState
function PowerCapability:get() end
---@param fn fun(value: PowerState): any
---@return Signal
function PowerCapability:map(fn) end
---@param command "set_profile"
---@param ... any
function PowerCapability:invoke(command, ...) end

---@class PrivacyCapability: Capability
local PrivacyCapability = {}
---@return PrivacyState
function PrivacyCapability:get() end
---@param fn fun(value: PrivacyState): any
---@return Signal
function PrivacyCapability:map(fn) end

---@class SysinfoCapability: Capability
local SysinfoCapability = {}
---@return SysinfoState
function SysinfoCapability:get() end
---@param fn fun(value: SysinfoState): any
---@return Signal
function SysinfoCapability:map(fn) end
---@param command "configure"
---@param ... any
function SysinfoCapability:invoke(command, ...) end

---@class SystemCapability: Capability
local SystemCapability = {}
---@return SystemState
function SystemCapability:get() end
---@param fn fun(value: SystemState): any
---@return Signal
function SystemCapability:map(fn) end

---@class TrayCapability: Capability
local TrayCapability = {}
---@return TrayState
function TrayCapability:get() end
---@param fn fun(value: TrayState): any
---@return Signal
function TrayCapability:map(fn) end
---@param command "activate"|"menu_will_show"|"activate_menu_item"
---@param ... any
function TrayCapability:invoke(command, ...) end

---@class UpdatesCapability: Capability
local UpdatesCapability = {}
---@return UpdatesState
function UpdatesCapability:get() end
---@param fn fun(value: UpdatesState): any
---@return Signal
function UpdatesCapability:map(fn) end
---@param command "configure"|"install"
---@param ... any
function UpdatesCapability:invoke(command, ...) end

---@class WorkspacesCapability: Capability
local WorkspacesCapability = {}
---@return WorkspacesState
function WorkspacesCapability:get() end
---@param fn fun(value: WorkspacesState): any
---@return Signal
function WorkspacesCapability:map(fn) end
---@param command "focus"
---@param ... any
function WorkspacesCapability:invoke(command, ...) end

--- Renderer-sourced members ---------------------------------------------------------------------
-- Not capabilities and not in `shared::CAPABILITIES`: these come from the renderer's own state, so
-- they carry no commands and are written by hand rather than derived from a payload struct.

---@class Screen
---@field name string Matches a surface's `monitor`.
---@field width integer Logical pixels.
---@field height integer
---@field scale number
---@field refresh number Hz. `0` for an output with no current mode, such as a virtual one.

---@class RescueState
---@field is_rescue boolean
---@field error_log string

---@class ObliskVersion
---@field major integer
---@field minor integer
---@field patch integer

---@class Oblisk
---@field audio AudioCapability
---@field network NetworkCapability
---@field bluetooth BluetoothCapability
---@field tray TrayCapability
---@field notifications NotificationsCapability
---@field mpris MprisCapability
---@field sysinfo SysinfoCapability
---@field keyboard KeyboardCapability
---@field privacy PrivacyCapability
---@field updates UpdatesCapability
---@field lock LockCapability
---@field battery BatteryCapability
---@field system SystemCapability
---@field brightness BrightnessCapability
---@field workspaces WorkspacesCapability
---@field power PowerCapability
---@field applications ApplicationsCapability
---@field screens Signal A `Screen[]`. Renderer-sourced, seeded to an empty list, and the one signal with a value at first evaluation (ADR-0041).
---@field rescue Signal A `RescueState`. Renderer-sourced, no commands (ADR-0046).
---@field version ObliskVersion Three integers a config can compare. Not a signal.
---@field config_dir string The directory `shell.lua` was loaded from, so a config can name a file it ships beside itself. Not a signal.
oblisk = {}
