//! `oblisk init`: makes a config directory an editable project. Writes two things, never the
//! config: `.luarc.json`, pointing lua-language-server at the stubs (copied out when no packaged
//! copy exists), and a starter `shell.lua`, only when none exists.

use std::io;
use std::path::{Path, PathBuf};

/// The five stub files, compiled in: lua-language-server reads from disk, not a binary, so
/// embedding doesn't remove the need to write them. It buys `cargo install`, which places no data
/// files, finding them instead under `$PREFIX/share`.
const EMBEDDED_STUBS: &[(&str, &str)] = &[
    ("globals.lua", include_str!("../../lua-meta/globals.lua")),
    ("nodes.lua", include_str!("../../lua-meta/nodes.lua")),
    ("oblisk.lua", include_str!("../../lua-meta/oblisk.lua")),
    ("signals.lua", include_str!("../../lua-meta/signals.lua")),
    ("surfaces.lua", include_str!("../../lua-meta/surfaces.lua")),
];

/// The config `init` writes when a directory has none: a file, not a string literal, so `just
/// lua` parses it with `luac -p` alongside every other Lua in the tree.
const STARTER_SHELL_LUA: &str = include_str!("../../share/starter/shell.lua");

/// The line the generator stamps into `oblisk.lua`'s header, written by `stubs::render` and read
/// here: a coupling held together only by
/// `stubs::tests::the_generated_stub_stamps_a_version_that_reads_back`. The alternative was
/// compiling the whole generator into the shipped binary just to keep this constant beside it.
const VERSION_MARKER: &str = "-- GENERATED by `supervisor/src/stubs.rs` for oblisk ";

/// The version a stub directory was generated for, read from `oblisk.lua`'s header. `None` when
/// the directory has no readable `oblisk.lua` or its header predates the stamp: either way, this
/// cannot be trusted to describe the running engine.
pub fn stub_version(dir: &Path) -> Option<String> {
    let text = std::fs::read_to_string(dir.join("oblisk.lua")).ok()?;
    let line = text.lines().take(8).find(|line| line.starts_with(VERSION_MARKER))?;
    Some(line.trim_start_matches(VERSION_MARKER).split_whitespace().next()?.trim_end_matches('.').to_string())
}

/// Where an installed copy of the stubs lives, resolved from the running binary the same way
/// `renderer_binary_path` resolves its sibling: `$PREFIX/lib/oblisk/oblisk` implies
/// `$PREFIX/share/oblisk/lua-meta`. `None` is the normal answer for `cargo install` and `target/`.
pub fn packaged_stub_dir() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let exe_dir = exe.parent()?;
    // Two layouts, tried in order: `just install` puts the binary in `$PREFIX/lib/oblisk` (prefix
    // two levels up), a flat install puts it in `$PREFIX/bin` (one level up). Checked, not assumed:
    // getting it wrong is silent, `init` falling back to embedded stubs the package kept current.
    ["../..", ".."]
        .iter()
        .map(|up| exe_dir.join(up).join("share").join("oblisk").join("lua-meta"))
        .find(|dir| dir.is_dir())
        .and_then(|dir| dir.canonicalize().ok())
}

/// Where `init` writes the embedded stubs when no packaged copy exists:
/// `$XDG_DATA_HOME/oblisk/lua-meta`, falling back to `$HOME/.local/share`. Outside the config
/// directory on purpose, see the note at its one call site.
fn user_stub_dir() -> io::Result<PathBuf> {
    if let Some(data_home) = std::env::var_os("XDG_DATA_HOME") {
        return Ok(PathBuf::from(data_home).join("oblisk").join("lua-meta"));
    }
    let home = std::env::var_os("HOME")
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "neither XDG_DATA_HOME nor HOME is set"))?;
    Ok(PathBuf::from(home).join(".local").join("share").join("oblisk").join("lua-meta"))
}

/// Writes `path` unless it exists, reporting which it did. `force` overwrites.
fn write_unless_present(path: &Path, contents: &str, force: bool) -> io::Result<bool> {
    if path.exists() && !force {
        println!("  kept    {} (exists)", path.display());
        return Ok(false);
    }
    std::fs::write(path, contents)?;
    println!("  wrote   {}", path.display());
    Ok(true)
}

/// The `.luarc.json` body, pointing `workspace.library` at `stub_dir`.
///
/// An absolute path: `workspace.library` resolves a relative one against the workspace root (the
/// config directory), not wherever stubs live, so a symlink wouldn't help either, since the path
/// must be known at init time. `runtime.path` mirrors the engine's own `package.path`, and
/// `runtime.builtin` removes the libraries ADR-0048 cut, so the editor refuses `io.open` and
/// `os.execute` like the VM does.
fn luarc_json(stub_dir: &Path) -> String {
    format!(
        r#"{{
  "$schema": "https://raw.githubusercontent.com/LuaLS/vscode-lua/master/setting/schema.json",
  "runtime.version": "Lua 5.4",
  "runtime.path": ["?.lua", "?/init.lua"],
  "runtime.pathStrict": true,
  "runtime.builtin": {{
    "io": "disable",
    "debug": "disable",
    "os": "disable",
    "jit": "disable",
    "ffi": "disable"
  }},
  "workspace.library": ["{}"],
  "workspace.checkThirdParty": false
}}
"#,
        stub_dir.display()
    )
}

/// `oblisk check`: evaluates the config and reports what it declares.
///
/// Re-execs the Renderer: the Supervisor has no `mlua` or loader, so only a real evaluation can
/// catch `require` failures and property errors. One evaluation path serves both check and boot.
pub fn check(config_dir: &Path) -> Result<String, String> {
    let renderer =
        crate::generation::renderer_binary_path().map_err(|err| format!("cannot find the renderer: {err}"))?;
    let output = std::process::Command::new(&renderer)
        .env(shared::CHECK_ENV, "1")
        .env(shared::CONFIG_DIR_ENV, config_dir)
        .output()
        .map_err(|err| format!("cannot run {}: {err}", renderer.display()))?;
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    if output.status.success() {
        Ok(stdout)
    } else {
        Err(String::from_utf8_lossy(&output.stderr).trim_end().to_string())
    }
}

pub fn run(config_dir: &Path, force: bool) -> Result<(), Box<dyn std::error::Error>> {
    run_into(config_dir, force, None)
}

/// [`run`], with the user stub directory injectable: `None` in production, for
/// [`user_stub_dir`]'s `$XDG_DATA_HOME` lookup, a `tempdir` in tests, to avoid `set_var`. Resolved
/// lazily, not as an argument default, so a packaged install with neither var set still works.
fn run_into(config_dir: &Path, force: bool, user_stubs: Option<&Path>) -> Result<(), Box<dyn std::error::Error>> {
    std::fs::create_dir_all(config_dir)?;
    println!("oblisk init: {}", config_dir.display());

    // A packaged install upgrades its stubs with the package, so pointing at them beats copying
    // them: a copied stub describing a different engine than the one running is worse than none.
    let running = env!("CARGO_PKG_VERSION");
    let stub_dir = match packaged_stub_dir() {
        Some(dir) => {
            // A packaged directory belongs to the package manager: this reports a mismatch and
            // changes nothing, rewriting files under `$PREFIX/share` being the wrong fix for that.
            match stub_version(&dir) {
                Some(found) if found != running => println!(
                    "  stubs   {} (packaged, generated for {found}, this is oblisk {running} -- the install is inconsistent)",
                    dir.display()
                ),
                _ => println!("  stubs   {} (packaged)", dir.display()),
            }
            dir
        }
        None => {
            // `$XDG_DATA_HOME/oblisk/lua-meta`, deliberately outside the config directory:
            // `watcher.rs` reloads the shell on any `.lua` file under it, so stubs living there
            // would make `oblisk init` restyle a running bar on every refresh. Also not config.
            let dir = match user_stubs {
                Some(dir) => dir.to_path_buf(),
                None => user_stub_dir()?,
            };
            // Rewritten whenever the version differs, left alone when it matches. These are
            // generated files this binary owns, not config: a stub from an older oblisk silently
            // describes fields that no longer exist and misses ones that do, worse than none.
            let existing = stub_version(&dir);
            if existing.as_deref() == Some(running) {
                println!("  stubs   {} (current)", dir.display());
            } else {
                if let Some(found) = existing {
                    println!("  stubs   {} (was generated for {found}, refreshing for {running})", dir.display());
                }
                std::fs::create_dir_all(&dir)?;
                for (name, contents) in EMBEDDED_STUBS {
                    write_unless_present(&dir.join(name), contents, true)?;
                }
            }
            dir
        }
    };

    write_unless_present(&config_dir.join(".luarc.json"), &luarc_json(&stub_dir), force)?;
    write_unless_present(&config_dir.join("shell.lua"), STARTER_SHELL_LUA, force)?;
    println!("\nOpen {} in an editor with lua-language-server.", config_dir.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // The `ENV` mutex that used to live here serialized every test touching `$XDG_DATA_HOME`,
    // because `run` resolved its stub directory through it. `run_into` takes that directory as an
    // argument, so no test here reads or writes the environment and there is nothing left to
    // serialize -- and none of them can write into the developer's real `~/.local/share` any
    // more, which the reader tests did whenever the checked-in stub version differed.

    /// `packaged_stub_dir` fails silently when it is wrong: `init` falls through to the embedded
    /// copy and writes stubs that the package would otherwise have kept current, so the user ends
    /// up with a stale schema and no error anywhere. It was wrong once, by exactly one `parent()`.
    ///
    /// Builds both installed layouts as directory trees and resolves against them directly, rather
    /// than re-execing an installed binary, so this runs in a normal `cargo test`.
    #[test]
    fn both_installed_layouts_resolve_to_the_packaged_stub_directory() {
        let root = tempfile::tempdir().unwrap();
        for (exe_rel, label) in [("lib/oblisk/oblisk", "just install"), ("bin/oblisk", "flat prefix")] {
            let prefix = root.path().join(label.replace(' ', "-"));
            let exe = prefix.join(exe_rel);
            std::fs::create_dir_all(exe.parent().unwrap()).unwrap();
            std::fs::write(&exe, b"").unwrap();
            let stubs = prefix.join("share/oblisk/lua-meta");
            std::fs::create_dir_all(&stubs).unwrap();

            let exe_dir = exe.parent().unwrap();
            let found = ["../..", ".."]
                .iter()
                .map(|up| exe_dir.join(up).join("share").join("oblisk").join("lua-meta"))
                .find(|dir| dir.is_dir())
                .and_then(|dir| dir.canonicalize().ok());
            assert_eq!(found, Some(stubs.canonicalize().unwrap()), "{label} layout must resolve its stubs");
        }
    }

    /// The whole point of the stamp: a stub directory left behind by an older oblisk has to be
    /// rewritten, because it describes fields that no longer exist and misses ones that do, with
    /// no error anywhere to say so.
    #[test]
    fn stubs_generated_for_another_version_are_refreshed() {
        let data = tempfile::tempdir().unwrap();
        let config = tempfile::tempdir().unwrap();
        let stubs = data.path().join("oblisk/lua-meta");

        run_into(config.path(), false, Some(&stubs)).unwrap();
        assert_eq!(stub_version(&stubs).as_deref(), Some(env!("CARGO_PKG_VERSION")));

        let oblisk_lua = stubs.join("oblisk.lua");
        let aged = std::fs::read_to_string(&oblisk_lua).unwrap().replace(env!("CARGO_PKG_VERSION"), "0.0.9");
        std::fs::write(&oblisk_lua, aged).unwrap();
        assert_eq!(stub_version(&stubs).as_deref(), Some("0.0.9"));

        run_into(config.path(), false, Some(&stubs)).unwrap();
        assert_eq!(
            stub_version(&stubs).as_deref(),
            Some(env!("CARGO_PKG_VERSION")),
            "a stale stub directory must be rewritten, not left for the language server to lie from"
        );
    }

    /// A header with no stamp at all reads the same as a wrong one: not trustworthy.
    #[test]
    fn stubs_with_no_version_line_have_no_version() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("oblisk.lua"),
            "---@meta
-- hand-written, once
",
        )
        .unwrap();
        assert_eq!(stub_version(dir.path()), None);
    }

    /// A binary with no packaged stubs beside it must say so rather than pointing at a directory
    /// that does not exist, which would leave the editor silently completing nothing.
    #[test]
    fn a_prefix_without_stubs_resolves_to_nothing() {
        let root = tempfile::tempdir().unwrap();
        let exe_dir = root.path().join("lib/oblisk");
        std::fs::create_dir_all(&exe_dir).unwrap();
        let found = ["../..", ".."]
            .iter()
            .map(|up| exe_dir.join(up).join("share").join("oblisk").join("lua-meta"))
            .find(|dir| dir.is_dir());
        assert_eq!(found, None);
    }

    #[test]
    fn init_writes_a_luarc_and_a_shell_lua_and_keeps_an_existing_one() {
        let dir = tempfile::tempdir().unwrap();
        let config = dir.path().join("oblisk");
        std::fs::create_dir_all(&config).unwrap();
        std::fs::write(config.join("shell.lua"), "-- mine\n").unwrap();

        run_into(&config, false, Some(&dir.path().join("stubs"))).unwrap();

        assert!(config.join(".luarc.json").is_file());
        assert_eq!(
            std::fs::read_to_string(config.join("shell.lua")).unwrap(),
            "-- mine\n",
            "init must never overwrite a config someone already wrote"
        );
    }

    #[test]
    fn force_overwrites_the_starter_config() {
        let dir = tempfile::tempdir().unwrap();
        let config = dir.path().to_path_buf();
        std::fs::write(config.join("shell.lua"), "-- mine\n").unwrap();
        run_into(&config, true, Some(&config.join("stubs"))).unwrap();
        assert_ne!(std::fs::read_to_string(config.join("shell.lua")).unwrap(), "-- mine\n");
    }

    /// The `workspace.library` path has to be absolute, or the editor resolves it against the
    /// config directory and finds nothing, with no error anywhere.
    #[test]
    fn the_generated_luarc_points_at_an_absolute_stub_directory() {
        let dir = tempfile::tempdir().unwrap();
        run_into(dir.path(), false, Some(&dir.path().join("stubs"))).unwrap();
        let luarc: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.path().join(".luarc.json")).unwrap()).unwrap();
        let library = luarc["workspace.library"][0].as_str().unwrap();
        assert!(Path::new(library).is_absolute(), "workspace.library must be absolute, got {library}");
        assert!(Path::new(library).join("oblisk.lua").is_file(), "the stub directory must actually hold the stubs");
    }
}
